### ISSUE TITLE
Error running makeOrgPackage

### ISSUE THREAD

**Issue by joonhoon** [Bioconductor/AnnotationForge#1]
Hello,
The change from  .lookupSpeciesFromTaxId() to lookup_organism_by_tax_id() in 18a9f8dec4f9e462976b1eb889c099c2d1aa137b is causing an error when running makeOrgPackage.

`library("AnnotationForge")`
`makeOrgPackage(version = '1.0', maintainer = 'maintainer', author = 'author', tax_id = 1)`
> Error in .makeOrgPackage(data, version = version, maintainer = maintainer, : 'tax_id' must be a single string
> Traceback:
> 
> 1. makeOrgPackage(version = "1.0", maintainer = "maintainer", author = "author", 
>  .     tax_id = 1)
> 2. .makeOrgPackage(data, version = version, maintainer = maintainer, 
>  .     author = author, outputDir = outputDir, tax_id = tax_id, 
>  .     genus = genus, species = species, goTable = goTable, verbose = verbose)
> 3. stop("'tax_id' must be a single string")

`makeOrgPackage(version = '1.0', maintainer = 'maintainer', author = 'author', tax_id = '1')`
> Error in GenomeInfoDb:::lookup_organism_by_tax_id(tax_id): isSingleNumber(tax_id) is not TRUE
> Traceback:
> 
> 1. makeOrgPackage(version = "1.0", maintainer = "maintainer", author = "author", 
>  .     tax_id = "1")
> 2. .makeOrgPackage(data, version = version, maintainer = maintainer, 
>  .     author = author, outputDir = outputDir, tax_id = tax_id, 
>  .     genus = genus, species = species, goTable = goTable, verbose = verbose)
> 3. GenomeInfoDb:::lookup_organism_by_tax_id(tax_id)
> 4. stopifnot(isSingleNumber(tax_id))

`sessionInfo()`

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS High Sierra 10.13.6
> 
> Matrix products: default
> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
> [1] AnnotationForge_1.22.1 AnnotationDbi_1.42.1   IRanges_2.14.10       
> [4] S4Vectors_0.18.3       Biobase_2.40.0         BiocGenerics_0.26.0   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.18         magrittr_1.5         bit_1.1-14          
>  [4] uuid_0.1-2           blob_1.1.1           stringr_1.3.1       
>  [7] tools_3.5.1          DBI_1.0.0            htmltools_0.3.6     
> [10] bit64_0.9-7          digest_0.6.15        crayon_1.3.4        
> [13] IRdisplay_0.5.0      repr_0.15.0          bitops_1.0-6        
> [16] base64enc_0.1-3      RCurl_1.95-4.11      IRkernel_0.8.12.9000
> [19] memoise_1.1.0        evaluate_0.11        RSQLite_2.1.1       
> [22] pbdZMQ_0.3-3         stringi_1.2.4        compiler_3.5.1      
> [25] XML_3.98-1.12        jsonlite_1.5        

Thank you.
Joonhoon

**Comment by hpages** [comment]
Hi Joonhoon,

Thanks for the reproducible example. This should be addressed in AnnotationForge 1.22.2 (BioC release) and 1.23.3 (BioC devel). [Here](https://github.com/Bioconductor/AnnotationForge/commit/28fff75f1f2f957189a1f28fb84d7779fab5b858) is the change.

H.

**Comment by lshep** [comment]
Hopefully this has been addressed;  @joonhoon if this is still an issue please let us know and we can reopen the issue.

**Comment by joonhoon** [comment]
It works for me. Thank you!
