### ISSUE TITLE
Fail to libaray the built package using makeOrgPackage

### ISSUE THREAD

**Issue by hcph** [Bioconductor/AnnotationForge#23]
Get the warinning： cannot remove file './org.Twheat.eg.sqlite', reason 'Permission denied'. Beg you help.
Here is the parameter I used:
makeOrgPackage(gene_info=wSym, chromosome=wChr, go=wGO,
               version="1.1",
               maintainer="Some One <hechao7021@someplace.org>",
               author="Some One <hechao7021@someplace.org>",
               outputDir = ".",
               tax_id="4565",
               genus="Taeniopygia",
               species="wheat",
               goTable="go")
#here is the output:
Populating genes table:
genes table filled
Populating gene_info table:
gene_info table filled
Populating chromosome table:
chromosome table filled
Populating go table:
go table filled
table metadata filled
'select()' returned many:1 mapping between keys and columns
Dropping GO IDs that are too new for the current GO.db
Populating go table:
go table filled
Populating go_bp table:
go_bp table filled
Populating go_cc table:
go_cc table filled
Populating go_mf table:
go_mf table filled
'select()' returned many:1 mapping between keys and columns
Populating go_bp_all table:
go_bp_all table filled
Populating go_cc_all table:
go_cc_all table filled
Populating go_mf_all table:
go_mf_all table filled
Populating go_all table:
go_all table filled
Creating package in ./org.Twheat.eg.db 
Now deleting temporary database file
[1] "./org.Twheat.eg.db"
Warning messages:
1: call dbDisconnect() when finished working with a connection 
2: In file.remove(dbFileName) :
  cannot remove file './org.Twheat.eg.sqlite', reason 'Permission denied'

**Comment by lshep** [comment]
Did the package get built in your working directory?

**Comment by fish2022Jul** [comment]
I encountered  the same problem. Any suggestion for it?

**Comment by fish2022Jul** [comment]
I got this error on Windows 11, R 4.2.1 (Rstudio) with **AnnotationDbi 1.58.** But when I switch to R 4.2.2 on Redhat7 AnnotationDbi 1.60. the error disperared. When I'm try to load the package to R 4.2.1, the system said I **must have AnnotationDbi_1.60 installed.**....So I updated it and load the generated library successfully.

**Comment by lshep** [comment]
Thank you for providing that additional information. So it seems like it may have been resolved in a later version of AnnotationDbi
