### ISSUE TITLE
failure with vignette example

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnnotationForge#26]
```
PC002284:ORGANISM vincentcarey$ Error in download.file(url, dest, quiet = TRUE) : 
  download from 'https://ftp.expasy.org/databases/uniprot/current_release/knowledgebase/idmapping/idmapping_selected.tab.gz' failed
In addition: Warning messages:
1: In download.file(url, tmp, quiet = TRUE, mode = "wb") :
  URL ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2pubmed.gz: cannot open destfile '/Users/vincentcarey/ORGANISM/gene2pubmed.gz', reason 'Permission denied'
2: In download.file(url, tmp, quiet
```
This after 1h+ and creation of 33GB sqlite table

**Comment by lshep** [comment]
I ran into this when investigating for the annotationhub release that runs this function  --   I had a 2h+ run that finished but I had to increase the timeout default higher in order for the idmapping file to download correctly.  It is very very large and takes awhile to download -- I added information into the man page for using option(timeout=) .  Let me know if you think it should go into the vignette too.
