### ISSUE TITLE
Error in h(simpleError(msg, call)) while trying calling makeOrgPackageFromNCBI()

### ISSUE THREAD

**Issue by lananh-ngn** [Bioconductor/AnnotationForge#35]
Hello,
I am trying to make and orgdb using makeOrgPackageFromNCBI() calling it like this (with my mail address my actual address):
`makeOrgPackageFromNCBI(
 version = "0.1",
 maintainer = "Lan Anh Nguyen <My mail address>",
 author = "Lan Anh Nguyen <My mail address>",
 tax_id = "4896",
 genus = "Schizosaccharomyces",
 species = "pombe",
 rebuildCache = FALSE
 )`

But I keep receiving this error:
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'table' in selecting a method for function '%in%': Timeout was reached: [www.ensembl.org:443] Operation timed out after 10005 milliseconds with 0 bytes received
In addition: Warning message:
call dbDisconnect() when finished working with a connection`

Is there a way to resolve this?
Thank you in advance,
Best regards,
Lan Anh

**Comment by lshep** [comment]
@grimbough there was a similar question on the support site too.  I wasn't able to reproduce.  Is this an intermittent biomaRt thing?

**Comment by grimbough** [comment]
Yes, this looks like a transient connection issue to the Ensembl server and was probably only temporary.

**Comment by lananh-ngn** [comment]
Hello again, 
I am sorry for the late answer, it was probably mine on the support site. I do not know what resolved the problem but I called several packages and it worked after that... Thank you for answering.
