### ISSUE TITLE
Why are all the calls to Ensembl set to version 80?

### ISSUE THREAD

**Issue by knokknok** [Bioconductor/AnnotationForge#44]
Could it be made an option propagated from makeOrgPackageFromNCBI?

**Comment by lshep** [comment]
Where are you referring? In other code, in examples, from other functions, a vignette?  

for makeOrgPackageFromNCBI man function default/man page, likely that was the release at the time of creation of the package.

**Comment by knokknok** [comment]
At least there:
getFastaSpeciesDirs
.getEnsemblData
