### ISSUE TITLE
"The 1st column must always be the gene ID 'GID'" error in makeOrgPackage

### ISSUE THREAD

**Issue by LichengXX** [Bioconductor/AnnotationForge#50]
I ran the makeOrgPackage Rscript with the following command:
makeOrgPackage(gene_info=gene_info,go=gene2go,ko=gene2ko,pathway=gene2pathway,
version="0.1",
maintainer = "name my_email",
author = "name my_email",
outputDir = ".",
tax_id="4081",
genus="Iaaa",
speceis="TAG",
goTable="go")

However, the program reports an error indicating that 
**Error in .makeOrgPackage(data, version = version, maintainer = maintainer,  : 
The 1st column must always be the gene ID 'GID'**
But the first column of my dataframe file is all 'GID' and the ids are uniform, as follows:
![image](https://user-images.githubusercontent.com/113669137/228238310-c6ec29a8-d822-4a86-a9d4-2309155051fc.png)
I have changed the other parameters and all produce the same error, which suggests that it is these dataframe files that are the problem.But I don't know what's wrong with my dataframe file.
Can anyone help me please?
Much appreciated.

**Comment by jmacdon** [comment]
@LichengXX This isn't the correct place for questions like this. Instead please post at support.bioconductor.org, and also use `dput` on a small portion of all your input `data.frames` so people can try to diagnose.
