### ISSUE TITLE
Package from AnnotationForge is not available for this version of R

### ISSUE THREAD

**Issue by phancanhtrinh** [Bioconductor/AnnotationForge#53]
Hi, 
Is there any person get this problem? 
I generated a database from AnnotationForge for GO term. Then I could not install it because of this error:

```
Warning in install.packages :   package ‘org.CalbicansSC5314V63.eg.sqlite’ is not available for this version of R  A version of this package for your version of R might be available elsewhere, see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
--
```
```

library(AnnotationForge)
makeOrgPackage(gene_info=fSym, go=fGO,
               version="0.1",
               maintainer="",
               author="",
               outputDir = ".",
               tax_id="",
               genus="Candida",
               species="albicansSC5314V63",
               goTable="go")

## then you can call install.packages based on the return value
install.packages("org.CalbicansSC5314V63.eg.sqlite")

```

![image](https://github.com/Bioconductor/AnnotationForge/assets/61386728/7df18732-da3e-45cf-9da3-66f886d5fc76)

I also did install the package that I generated last year. It had the same problem. I think this came from new version of R?

I hope some people can help me.
Thak you very much!

**Comment by jmacdon** [comment]
You should post questions like this on the support site (support.bioconductor.org) rather than here, as this is a misunderstanding on your part rather than an issue with the package.

The answer is

```
install.packages("org.CalbicansSC5324V63.eg.db", repos = NULL)
## or if on Windows
install.packages("org.CalbicansSC5324V63.eg.db", repos = NULL, type = "source")
```

**Comment by phancanhtrinh** [comment]
Thank you very much for your support!
