### ISSUE TITLE
i get the failed to remove file, permission denied error while analysing micrroarray data

### ISSUE THREAD

**Issue by Peter97221** [Bioconductor/AnnotationForge#55]
getGEOSuppFiles("GSE78721") 
above is the code i used  and the error is as below. can anyone help?
<html>
<body>

Error in getGEOSuppFiles("GSE78721") :    Failed to download C:/Users/naren/OneDrive/Documents/GSE78721/GSE78721_RAW.tar! In addition: Warning message: In file.remove(destfile) :   cannot remove file 'C:/Users/naren/OneDrive/Documents/GSE78721/GSE78721_RAW.tar', reason 'Permission denied'
--
 
> | >
>

</body>
</html>

**Comment by jmacdon** [comment]
This issue has nothing to do with the AnnotationForge package (you are using GEOquery, which is an entirely different package). In addition, this issue log is meant for actual bugs, not support. If you want support, post on https://support.bioconductor.org.
