### ISSUE TITLE
Error in .makeOrgPackage(data, version = version, maintainer = maintainer,  :    All elements of '...' must have unique names

### ISSUE THREAD

**Issue by liuliang577** [Bioconductor/AnnotationForge#56]
When I directly created a table file that met the requirements and used this function,
Error in .makeOrgPackage(data, version = version, maintainer = maintainer,  : 
  All elements of '...' must have unique names

BUT no duplicate rows found using Excel.
This makes me very confused. I spent a whole night but still couldn't solve this problem.

The following image is my original code, which has been smeared with some information to protect privacy.
<img width="600" alt="image" src="https://github.com/Bioconductor/AnnotationForge/assets/156409137/962da9b8-0713-4d15-98ee-b6e2e5fda4b9">
The following image is an Excel file that I created directly
<img width="540" alt="image" src="https://github.com/Bioconductor/AnnotationForge/assets/156409137/988b870f-16bd-40fb-bb21-086b14cffd75">

I would be very grateful to the person who solved this problem！

**Comment by jmacdon** [comment]
Please don't use this GitHub for support. Instead, post questions at support.bioconductor.org
